# Generated by Django 3.0.4 on 2020-04-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0003_auto_20200329_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='subcategories',
            field=models.ManyToManyField(null=True, to='services_manager.Categories'),
        ),
    ]
