# Generated by Django 3.0.4 on 2020-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0004_categories_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerstimeslot',
            name='day',
            field=models.CharField(max_length=10, null=True, verbose_name='days of week'),
        ),
    ]
