# Generated by Django 3.0.4 on 2020-04-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200403_0628'),
        ('services_manager', '0008_auto_20200406_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumertimeslotmapping',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='consumertimeslotmapping',
            name='booking_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Failed'), (3, 'Completed'), (4, 'Canceled')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='providerstimeslot',
            name='home_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=5, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('force_update', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
