# Generated by Django 3.0.4 on 2020-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0010_remove_consumertimeslotmapping_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertimeslotmapping',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
