# Generated by Django 3.0.4 on 2020-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0013_auto_20200413_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertimeslotmapping',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
