# Generated by Django 3.0.4 on 2020-04-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0014_consumertimeslotmapping_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertimeslotmapping',
            name='updated1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_manager.ProvidersTimeSlot'),
        ),
    ]
