# Generated by Django 3.0.4 on 2020-04-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0015_consumertimeslotmapping_updated1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumertimeslotmapping',
            old_name='updated1',
            new_name='time_slot',
        ),
    ]
