# Generated by Django 3.0.4 on 2020-04-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_manager', '0016_auto_20200413_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subcategories',
        ),
    ]
