# Generated by Django 3.0.4 on 2020-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accesstokens_phonetokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetokens',
            name='user',
        ),
        migrations.AddField(
            model_name='phonetokens',
            name='phone',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
