# Generated by Django 3.0.4 on 2020-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200327_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'consumer'), (2, 'provider'), (5, 'admin')], null=True),
        ),
    ]
