# Generated by Django 3.0.4 on 2020-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200327_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
