# Generated by Django 3.0.4 on 2020-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'consumer'), (2, 'provider'), (5, 'admin')], default=1, null=True),
        ),
    ]
