# Generated by Django 3.0.4 on 2020-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200327_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
