# Generated by Django 3.0.4 on 2020-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200327_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
