# Generated by Django 3.0.4 on 2020-03-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='phonetokens',
            name='phone',
        ),
        migrations.AddField(
            model_name='phonetokens',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
