# Generated by Django 3.0.4 on 2020-04-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200401_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12, verbose_name='lattitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12, verbose_name='longitude'),
        ),
    ]
